# Generated by Django 4.2 on 2023-04-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_status_post_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
